services:
  - type: web
    name: candidate-form-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: run
      - key: GOOGLE_API_KEY
        scope: run
    autoDeploy: true

  - type: static
    name: candidate-form-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://candidate-form-backend.onrender.com
    autoDeploy: true
